defaults:
  -
    scope:
      path: ""
    values:
      content: "testing"

prose:
  metadata:
    _proposals:
      - name: content
        field:
          element: textarea
          value: testing!
